### ISSUE TITLE
Intermittent failure "cache not found"

### ISSUE THREAD

**Issue by dopey** [actions/setup-go#272] opened 2022-09-30 21:28 UTC
**Description:**
Using the `cache: true` feature, action intermittently fails due to step "Post Install go" with error: `Error: There are no cache folders on the disk`. Occurring on multiple repositories in our org. 

**Action version:**
step-go@v3

go version go1.[18](https://github.com/smallstep/nosql/actions/runs/3161525130/jobs/5147207995#step:7:19).6 linux/amd64
**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
go 1.18.6

**Repro steps:**  
https://github.com/smallstep/nosql/actions/runs/3161525130/jobs/5147207995

**Expected behavior:**
Success

**Actual behavior:**
Failure

**Comment by dmitry-shibanov** [comment] 2022-10-02 11:26
Hello @dopey. Thank you for your report. It looks like an expected behaviour because it tries to save cache but the cache folders do not exist that is why it fails. Other jobs pass well because they have primary key for these dependencies and Go version.

**Comment by HTTP-iamcomingsoon** [comment] 2022-10-02 11:42
That's really  what we expected to be done in the previous days.

**Comment by dopey** [comment] 2022-10-05 05:26
@dmitry-shibanov hey, thanks for quick response. So, I understand this is expected behavior, but, how can I go about fixing from my end?

> Other jobs pass well because they have primary key for these dependencies and Go version.

I'm not sure why other jobs will have this, but this job does not. I haven't consciously set anything up differently.

Thanks!

**Comment by schmidtw** [comment] 2022-10-08 02:05
This fix was put in about a month ago, could it be released so we don't need to pin a specific hash?
https://github.com/actions/setup-go/issues/258

If it helps I'm using this version & the failures are gone.  They are just warnings.
```actions/setup-go@30b9ddff1180797dbf0efc06837929f98bdf7af7```

**Comment by e-korolevskii** [comment] 2022-10-19 07:01
Hi @dopey!

Yesterday we released a new version that includes a solution to this issue.
Could you confirm that it is now working as expected?

**Comment by e-korolevskii** [comment] 2022-10-21 07:16
At the moment I am closing this issue, but if there are additional questions, we can continue communication here or in a new one!

**Closed by e-korolevskii** 2022-10-21 07:16 UTC
Labels: bug
