### ISSUE TITLE
met issue with golang 1.18 standard package strings.Cut

### ISSUE THREAD

**Issue by Icarus9913** [actions/setup-go#254] opened 2022-08-11 06:48 UTC
**Description:**
I used `strings.Cut` in my project and our go.mod already updated to `golang 1.18.2` and I update `actions/setup-go` with go-version1.19, but there are some errors. Now I update them to `golang 1.19` and still met these errors

**Action version:**
actions/setup-go@v3
actions/checkout@v3

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
```text 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ needs.filter_changes.outputs.ref }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'

      - name: Checkout ENV go version
        run: go version

      # ==run unitest. I use ginkgo -v 
      - name: Run unitest
        id: unitest
        continue-on-error: true
        run: |
          sudo make unitest-tests 
```

**Log**
```text 
coverage: [no statements]
Failed to compile cmd:

# github.com/spidernet-io/spiderpool/pkg/workloadendpointmanager
Error: ../../../pkg/workloadendpointmanager/workloadendpoint_manager.go:292:16: undefined: strings.Cut
Error: ../../../pkg/workloadendpointmanager/workloadendpoint_manager.go:336:25: undefined: strings.Cut
Error: ../../../pkg/workloadendpointmanager/workloadendpoint_manager.go:341:25: undefined: strings.Cut
note: module requires Go 1.19

composite coverage: 85.1% of statements
exit status 1

make: *** [Makefile:268: unitest-tests] Error 1
Ginkgo ran 4 suites in 1m15.916056532s
```

**Comment by e-korolevskii** [comment] 2022-08-11 07:22
Hello @Icarus9913. Thank you for your report. We'll investigate the issue.

**Comment by Icarus9913** [comment] 2022-08-11 07:32
@e-korolevskii Thanks for your quick response.
You can check the CI details with the following links:
https://github.com/spidernet-io/spiderpool/runs/7781542284?check_suite_focus=true

**Comment by e-korolevskii** [comment] 2022-08-11 13:17
Hello @Icarus9913!

After the investigation, I return to you. As I was able to figure out, the problem is not with `setup-go`, but with the fact that you are using `sudo`.
You can try using `make` without `sudo` or see possible workarounds here: https://github.com/actions/setup-go/issues/104

I'm closing this issue, but you can always ask additional questions here or create a new one. 
Have a good day!

**Closed by e-korolevskii** 2022-08-11 13:17 UTC
Labels: bug

**Comment by Icarus9913** [comment] 2022-08-11 13:27
Got it! Resolved! 
Thank you very much!

**Comment by Icarus9913** [comment] 2022-08-12 03:52
@e-korolevskii 
Hi. What if I wanna use go in `root` User, what should I do ?

**Comment by Icarus9913** [comment] 2022-08-12 06:27
In my golang project, I will use `os.MkdirAll` create a filepath `/var/log/***`. 
The CI would give me an error `permission denied`

In this situation, I'm wondering what if I run the go project with `root` User

**Comment by e-korolevskii** [comment] 2022-08-17 07:19
Hello @Icarus9913!

Have you already tried the workarounds suggested in this [issue](https://github.com/actions/setup-go/issues/104)? Did they not work for you? Could you provide a workflow with errors?
