### ISSUE TITLE
Run 'go get ... ; go version' before 'go build ./...' breaks action

### ISSUE THREAD

**Issue by gallo-cedrone** [actions/setup-go#38] opened 2020-01-20 12:13 UTC
When building  with `go: [1.13]` in a windows environment making use of the `pwsh` as shell a pipeline step fails with no helpful log message if commands `go get [...] ; go version` are run before the build.

For example ([Logs](https://pipelines.actions.githubusercontent.com/sVoTQl5vw9sMTShDrnFxn6ARWxk4NGIrqh2xffkLtvUYGLr5KS/_apis/pipelines/1/runs/283/signedlogcontent/4?urlExpires=2020-01-20T12%3A15%3A05.9152511Z&urlSigningMethod=HMACV1&urlSignature=L57sfkVA%2B3yThvtzIgfmIuViFo2QvGXYr%2Bww128Gwh0%3D)):
```
    - name: test
      shell: pwsh
      run: |
        go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
        go version
        go build -v ./...
Output:
go version go1.13.6 windows/amd64
github.com/gallo-cedrone/nri-elasticsearch/vendor/github.com/newrelic/infra-integrations-sdk/data/event
##[error]Process completed with exit code 1.
```
And these ones succeed
```
    - name: MSBuild
      shell: pwsh
      run: |
        go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
        go build -v ./...
    - name: MSBuild
      shell: pwsh
      run: |
        go version
        go build -v ./...
    - name: MSBuild3
      shell: bash
      run: |
        go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
        go version
        go build -v ./...
```
This locally is not happening, using windows and the bash as shell is not happening, using the linux environment is not happening.

Honestly I do not understand what can cause this weird behaviour

**Comment by bryanmacfarlane** [comment] 2020-02-11 16:13
I don't believe this is the setup-go action since it repros not using it.

**Comment by bryanmacfarlane** [comment] 2020-02-11 16:14
@thboop since I think this was a powershell bug ... he has workarounds

**Comment by thboop** [comment] 2020-02-11 16:28
Hey @gallo-cedrone , thanks for the report!

This a powershell/powershell core bug. We have a related issue tracking it in the Actions Runner: https://github.com/actions/runner/issues/169

We are hoping to resolve it when Powershell 7 GA's.

It looks like you have found the workarounds (separate your multi-line step into individual steps or use a different shell).

I'm going to go ahead and close this issue as a dupe of the above, but feel free to reopen as needed.

**Closed by thboop** 2020-02-11 16:28 UTC
Labels: external
