### ISSUE TITLE
golang 1.18 support

### ISSUE THREAD

**Issue by pratikbin** [actions/setup-go#206] opened 2022-03-17 05:58 UTC
**Description:**
Since 1.18 is GA now, need `go-version: 1.18.x`

**Comment by dmke** [comment] 2022-03-17 22:58
Not sure if related, but `go-version: 1.x` also runs Go 1.17.7.

**Comment by arthurkushman** [comment] 2022-03-23 10:14
I'm trying to run GitHub Actions after updating repo to `Go 1.18` version and `setup-go` to `v3` and it's go version to 1.18, also updated `checkout` to `@v3` in context of compatibility - the error  https://github.com/arthurkushman/pgo/runs/5618443803?check_suite_focus=true

What should I do to make GitHub Actions work with setup-go?

**Comment by marko-zivic-93** [comment] 2022-03-24 13:42
Hello @pratikbin
Thank you very much for pointing this issue out!
The issue is fixed. 

In order to use version 1.18.x you can use the following yaml snippet:

```
steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.0"
```
@pratikbin can you please confirm that the issue is fixed?
@arthurkushman can you please create a separate issue dedicated to the problem you are experiencing?

**Comment by pratikbin** [comment] 2022-03-24 14:00
@marko-zivic-93 Yessir, It's working `go-version: "1.18"`

**Comment by vsafonkin** [comment] 2022-03-25 11:08
@dmke, you can use `check-latest` option for it:
```yaml
- name: Setup Go environment
  uses: actions/setup-go@v3
  with:
    go-version: 1.*
    check-latest: true
```
<img width="914" alt="Screenshot 2022-03-25 at 12 05 34 PM" src="https://user-images.githubusercontent.com/7628945/160109968-93e5df3f-a415-4ba8-8ada-978c2cd06f87.png">

**Comment by marko-zivic-93** [comment] 2022-03-25 11:09
Hello @pratikbin,
Thank you very much for confirming that everything works as intended!

@dmke please find the provided documentation explaining how to fix this issue here:
https://github.com/actions/setup-go#check-latest-version

**Comment by marko-zivic-93** [comment] 2022-03-25 11:10
I am going to close this issue. Please contact us if you have any problems regarding this topic.

**Closed by marko-zivic-93** 2022-03-25 11:10 UTC
Labels: feature request
