### ISSUE TITLE
Golang 1.15 was released over one month ago

### ISSUE THREAD

**Issue by alessio** [actions/setup-go#74] opened 2020-09-13 15:47 UTC
Hi!

Go 1.15 was [released on August 11th](https://blog.golang.org/go1.15), yet we can't yet [use it in our builds](https://github.com/cosmos/cosmos-sdk/pull/7014).

Please advise.

Thanks for considering.

(CC'ing @marbar3778)

**Comment by lrstanley** [comment] 2020-11-13 18:59
This is becoming a very annoying issue to have to work around. setup-go is constantly behind versions by quite a bit. When the Go team releases a new Go version that has fixes for various CVE's, it's critical to be able to pull that version and be able to release new versions/run new builds based off that new version.

The past 8 versions or so, I've been constantly behind, expecting to be able to run another build, and have it pull in an older version (sometimes more than one patch version behind!).

`setup-go` should really not require manual adjustments to get new versions. Maybe it's worth not reinventing the wheel, and utilizing something like https://github.com/travis-ci/gimme?

**Comment by circa10a** [comment] 2020-12-04 04:08
Maybe support `version : latest` ?

**Comment by hazcod** [comment] 2020-12-10 06:39
FYI I use a Docker image in `.github/` which I update automatically with dependabot.
```
      -
        id: vars
        run: |
          echo ::set-output name=go_version::$(grep '^FROM go' .github/go/Dockerfile | cut -d ' ' -f 2 | cut -d ':' -f 2)
          echo "Using Go version ${{ steps.vars.outputs.go_version }}"
      -
        name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
```

**Comment by circa10a** [comment] 2020-12-10 21:52
This will parse our the latest go version from the versions-manifest.json

``` 
-
        id: vars
        run: |
curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
          echo "Using Go version ${{ steps.vars.outputs.go_version }}"
      -
        name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
```

**Comment by circa10a** [comment] 2020-12-11 23:35
Alternatively:

```yaml
- id: vars
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
          echo "Using Go version ${{ steps.vars.outputs.go_version }}"
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
```

**Comment by tianon** [comment] 2020-12-15 00:53
> Maybe it's worth not reinventing the wheel, and utilizing something like https://github.com/travis-ci/gimme?

I can say that https://github.com/travis-ci/gimme isn't exactly well-maintained, but was designed such that it (ideally) doesn't have to be. :sweat_smile:

(I helped create it initially, although I'm not involved much anymore.)

**Comment by lrstanley** [comment] 2020-12-25 22:51
Looking at `go-versions`, seems it's manually updated via an action. Why not have have it update automatically (and only when needed)? Could it run once a day (or sooner)? `go-versions` doesn't have issues enabled, so can't ask there...

**Comment by Sergey-Murtazin** [comment] 2021-12-20 15:00
Hi, @alessio!
Thanks for your request!

We will consider whether to add check latest version functionality.

I close this issue because it's a duplicate of [73#](https://github.com/actions/setup-go/issues/73#)
Feel free to contact us and/or reopen this issue if you have any questions

**Closed by Sergey-Murtazin** 2021-12-20 15:00 UTC
Labels: feature request
