### ISSUE TITLE
A way to specify which go ARCH to download

### ISSUE THREAD

**Issue by deogracia** [actions/setup-go#60] opened 2020-07-04 10:31 UTC
Hi :D 

I was trying to make setup-go to donwload 386 version on ubuntu 18.04.
I tried override GOARCH before calling setup-go, but it's useless since it uses "os.arch()" (https://github.com/actions/setup-go/blob/master/src/system.ts#L20, https://github.com/actions/setup-go/blob/master/src/installer.ts#L37)

Is there a way to specify which ARCH version setup-go have to download and setup?

**Comment by umbynos** [comment] 2020-11-05 17:48
I've got the same problem

**Comment by Sergey-Murtazin** [comment] 2021-12-20 12:02
Hi, @deogracia!
Thanks for your request!

We are considering whether to add this functionality to the next release.

I close this issue because it's a duplicate of [Support for arm 32-bit](https://github.com/actions/setup-go/issues/106)
Feel free to contact us and/or reopen this issue if you have any questions.

**Closed by Sergey-Murtazin** 2021-12-20 12:02 UTC
Labels: feature request

**Comment by deogracia** [comment] 2022-01-09 21:07
Thanks @Sergey-Murtazin
