### ISSUE TITLE
Go1.16 not in either manifest, but available for download, but not working.

### ISSUE THREAD

**Issue by cameronelliott** [actions/setup-go#103] opened 2021-01-29 03:27 UTC
I'm trying to use setup-go to use Go1.16, it is a non-stable version with both a beta and RC version available.

It cannot be found in either of the manifests listed on the [Readme](https://github.com/actions/setup-go/blob/main/README.md):
https://github.com/actions/go-versions/blob/main/versions-manifest.json
https://storage.googleapis.com/golang

But, both Go 1.16-beta1 and Go 1.16 are available for download, but I have utterly failed to
get those downloads to work with this action:
https://golang.org/dl/go1.16rc1.linux-amd64.tar.gz
https://golang.org/dl/go1.16beta1.linux-amd64.tar.gz

Can the download URLs be provided somehow to this action?
Thanks

**Comment by atc0005** [comment] 2021-01-29 08:06
@cameronelliott See #96 and #92 (re beta). You may have similar results using the RC1 release.

**Comment by andig** [comment] 2021-02-05 17:44
RC is not working although this is the exact syntax from the README (there as 1.14):

    Unable to find Go version '1.16.0-rc1' for platform linux and architecture x64.

**Comment by gandarez** [comment] 2021-02-22 15:36
`Go` just got 1.16 released. Does it get to work?

**Comment by Sergey-Murtazin** [comment] 2021-11-17 11:21
Hello @cameronelliott. 

Thank you for your report. 
I’ve tried to reproduce the issue, but it looks like everything [works as expected](https://github.com/Sergey-Murtazin/hello-world/actions/runs/1471281989). 
For now I’m closing the issue but if you have any concerns feel free to contact us.

**Closed by Sergey-Murtazin** 2021-11-17 11:21 UTC
Labels: bug
