### ISSUE TITLE
Allow skipping of local cache

### ISSUE THREAD

**Issue by berndverst** [actions/setup-go#129] opened 2021-07-15 22:15 UTC
Currently when specifying a minor version such as 1.16 this action installs the cached version first. The problem is that [cached versions](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#go) on shared runners do not get updated frequently.

We need a way to skip the local cache. If this is already possible it needs to be documented.

At this time 1.16 specified installs 1.16.5, even though `go-versions` lists `1.16.6` since 3 days ago and the release itself was 5+ days ago.

It appears `actions/virtual-environments` has a weekly release cadence and based on timing this can mean up to 2 weeks lag for patch releases. Due to CVEs it is therefore advisable to be able to skip the actions (virtual environment) cache.

Perhaps there could be an option to check against `go-versions` and only pull from there if the local cache does not have the latest version in `go-versions`.

**Comment by berndverst** [comment] 2021-07-15 22:18
FYI @pkedy @artursouza @wcs1only this is the problem we are having with the [Dapr](https://dapr.io) workflows.

**Comment by tritu** [comment] 2021-12-15 11:16
Yes, do appreciate this feature added.

**Comment by Sergey-Murtazin** [comment] 2021-12-20 12:12
Hi, @berndverst!
Thanks for your request!

We are considering whether to add this functionality in the next release.

I close this issue because it's a duplicate of [73#](https://github.com/actions/setup-go/issues/73#).
Feel free to contact us and/or reopen this issue if you have any questions.

**Closed by Sergey-Murtazin** 2021-12-20 12:12 UTC
Labels: feature request
