### ISSUE TITLE
Using `go-version-file` requires `go.sum` file to be present

### ISSUE THREAD

**Issue by kare** [actions/setup-go#270] opened 2022-09-30 15:46 UTC
**Description:**
I'm using a shared workflow to build Go packages. In the shared workflow I specify Go version with `go-version-file: go.mod`. The project I'm building with the shared workflow contains `go.mod` file to specify Go version but it doesn't contain a `go.sum` file.

Build fails with error:
```
Error: Dependencies file is not found in /home/runner/work/infra/infra. Supported file pattern: go.sum
```

**Workaround**
Adding an empty `go.sum` file to the repository will workaround this issue.

**Action version:**
v3.3.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.18

**Repro steps:**  

GitHub Actions Log:
```
Run actions/setup-go@v3.3.0
[2](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:2)
  with:
[3](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:3)
    go-version-file: go.mod
[4](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:4)
    check-latest: true
[5](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:5)
    cache: true
[6](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:6)
    token: ***
[7](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:8)
Setup go version spec 1.18
[8](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:9)
Attempting to resolve the latest version from the manifest...
[9](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:10)
matching 1.18...
[10](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:11)
Resolved as '1.18.6'
[11](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:12)
Found in cache @ /opt/hostedtoolcache/go/1.18.6/x64
[12](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:13)
Added go to the path
[13](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:14)
Successfully set up Go version 1.18
[14](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:15)
/opt/hostedtoolcache/go/1.18.6/x64/bin/go env GOMODCACHE
[15](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:16)
/opt/hostedtoolcache/go/1.18.6/x64/bin/go env GOCACHE
[16](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:17)
/home/runner/go/pkg/mod
[17](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:18)
/home/runner/.cache/go-build
[18](https://github.com/kare/infra/actions/runs/3159902983/jobs/5143733422#step:3:19)
Error: Dependencies file is not found in /home/runner/work/infra/infra. Supported file pattern: go.sum
```

**Expected behavior:**
Project should be built without `go.sum` file.

**Actual behavior:**
Project build stops on error.

**Comment by marko-zivic-93** [comment] 2022-10-03 10:59
Hello @kare 
Thank you for your issue. We will take a look at it as soon as possible and come back to you :)

**Comment by dmitry-shibanov** [comment] 2022-10-03 20:54
Hello @kare. Could you please provide a public repository to reproduce the issue ?

**Comment by flowchartsman** [comment] 2022-10-08 15:20
This is biting me as well. Kind of annoying, since my library does not need a go sum. :-\

**Comment by flowchartsman** [comment] 2022-10-08 15:22
I'm also running into this. In my case, my library uses generics (so it needs go >=1.18), however it does not have dependencies, so it does not have or need a `go.sum`. Without making a fake `go.sum`, the action will not work.

**Comment by jgustie** [comment] 2022-10-13 17:07
I am also encountering this issue under slightly different circumstances: I am using `go-version-file: foobar/go.mod` which works fine; but if I set `cache: true` I start getting the failure. There is no `/go.sum` in my case, but there is a `/foobar/go.sum`.

**Comment by vsafonkin** [comment] 2022-10-19 11:57
Hello @kare, @flowchartsman, @jgustie. Unfortunately, I can't reproduce this issue, for example:
https://github.com/vsafonkin/test-repo/actions/runs/3281310762

```yaml
- uses: actions/setup-go@v3.3.0
  with:
    go-version-file: 'go.mod'
    check-latest: true
```

It works as expected without any `go.sum` file.

Could you please provide a sample demo for this bug?
Thank you.

**Comment by vsafonkin** [comment] 2022-10-19 12:05
Hello @kare, @flowchartsman, unfortunately I can't reproduce this bug, for example sample workflow run:
https://github.com/vsafonkin/test-repo/actions/runs/3281310762

```yaml
- uses: actions/setup-go@v3.3.0
  with:
  go-version-file: 'go.mod'
    check-latest: true
```

It works as expected.

Could you please provide some sample demo or link to the failed workflow run for this bug?
Thank you.

**Comment by vsafonkin** [comment] 2022-10-31 07:45
Hi @kare, I'm going to close this issue, feel free to reopen it if you have any concerns, thank you!

**Closed by vsafonkin** 2022-10-31 07:45 UTC
Labels: bug

**Comment by nothub** [comment] 2023-02-12 15:02
@vsafonkin the bug will only trigger if `cache: true` is defined.
