### ISSUE TITLE
Cache doesn't work with Go 1.14

### ISSUE THREAD

**Issue by barrettj12** [actions/setup-go#304] opened 2022-12-13 01:06 UTC
**Description:**
When I use this action with Go 1.14 and the cache enabled, it fails with
```
Error: Could not get cache folder paths.
```

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Go 1.14

**Repro steps:**  
Run the following step:
```yaml
      uses: actions/setup-go@v3
      with:
        go-version: 1.14
        cache: true
```

See sample test run here:
https://github.com/canonical/pebble/actions/runs/3681163227/jobs/6227686103

**Comment by dmitry-shibanov** [comment] 2022-12-13 01:29
Hello @barrettj12. Thank you for your report. We'll investigate the issue.

**Comment by e-korolevskii** [comment] 2022-12-13 14:48
Hello @barrettj12 

I think the problem is that we use the `GOMODCACHE` and `GOCACHE` variables to implement the cache function. But in `go 1.14`, the `GOMODCACHE` variable is missing.

**Comment by barrettj12** [comment] 2022-12-13 23:32
Yeah, seems for Go <= 1.14, the default should be `$GOPATH/pkg/mod`.

**Comment by e-korolevskii** [comment] 2022-12-19 10:35
Hello @barrettj12 

Thanks for your report! It's fixed now! The [changes ](https://github.com/actions/setup-go/pull/305)will be available in the next release. 
I am closing this issue for now!

**Closed by e-korolevskii** 2022-12-19 10:35 UTC
Labels: bug
