### ISSUE TITLE
can't support multi-arch go environment

### ISSUE THREAD

**Issue by xiaods** [actions/setup-go#166] opened 2021-11-10 11:25 UTC
**Description:**
use github action with strategy matrix arch.

https://github.com/xiaods/k8e/blob/master/.github/workflows/release.yml

**Action version:**
V2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

uses: actions/setup-go@v2
**Repro steps:**  
I want to build with multi-arch. follow the github action tutorial, I have already setup matrix virtual environment to build , but I found the golang binary always is amd64, even if I set goos is arm64.

**Expected behavior:**
support install go with arm64 version

**Actual behavior:**
only support amd64 version golang

**Comment by Sergey-Murtazin** [comment] 2021-12-20 12:01
Hi, @xiaods !
Thanks for your request!

Currently setup-go action install compiler with the same arch as a VM where your code is running. 
We are considering whether to add set compiler arch functionality to the next release.

I close this issue because it's a duplicate of [Support for arm 32-bit](https://github.com/actions/setup-go/issues/106)
Feel free to contact us and/or reopen this issue if you have any questions

**Closed by Sergey-Murtazin** 2021-12-20 12:01 UTC
Labels: feature request

**Comment by AkashKumar7902** [comment] 2023-10-09 14:08
@Sergey-Murtazin is there any workaround, apart from hosting a action runner machine ?
