### ISSUE TITLE
Caching doesn't work with cross-compiling

### ISSUE THREAD

**Issue by barrettj12** [actions/setup-go#298] opened 2022-12-05 05:18 UTC
**Description:**
When using this action with `cache: true`, the cache doesn't seem to work for cross-compiling. Our workflow is essentially:
```yaml
    - uses: actions/setup-go@v3
      with:
        cache: true
    - run: GOOS=... GOARCH=... go install ...
```
We get a nice speed-up when the GOOS and GOARCH match the OS/arch of the runner. If they don't match, there is no speedup of the build process. See these two action runs:
https://github.com/barrettj12/juju/actions/runs/3616873783/attempts/1
https://github.com/barrettj12/juju/actions/runs/3616873783/attempts/2

I suspect this is because the action only caches build artifacts for the runner's OS and arch.

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Go 1.19

**Comment by e-korolevskii** [comment] 2022-12-05 08:31
Hi @barrettj12 

We will investigate this issue and come back to you.

**Comment by dmitry-shibanov** [comment] 2023-01-09 10:34
Hello @barrettj12. I think it is an expected behaviour because you have multiple jobs with different configuration for OS and Architecture. It has different dependencies and cache, that is why the first job to save cache gets time improvements the other one does not have same cache.

**Comment by barrettj12** [comment] 2023-01-09 22:10
Hi @dmitry-shibanov, is it possible to cache build artifacts for a different OS / arch then?

**Comment by dmitry-shibanov** [comment] 2023-01-24 10:47
Hello @barrettj12. For now I'm going to close the issue. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2023-01-24 10:47 UTC
Labels: bug
