### ISSUE TITLE
Failure of "Validate 'setup-go'" on macos-latest

### ISSUE THREAD

**Issue by 178inaba** [actions/setup-go#474] opened 2024-04-27 16:20 UTC
**Description:**
"Validate 'setup-go'" is failing.
The cause is that the architecture of macos-latest has become arm64.
https://github.com/actions/runner-images

**Action version:**
v5.0.0

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
- 1.8.6
- 1.9
- 1.12.16
- 1.13.11
- 1.14
- 1.14.3

**Repro steps:**  
https://github.com/actions/setup-go/actions/runs/8855760631
https://github.com/actions/setup-go/actions/runs/8855760631/job/24321136893#step:3:12

**Expected behavior:**
The successful "Validate 'setup-go'" workflow.

**Actual behavior:**
The "Validate 'setup-go'" fails.

**Comment by aparnajyothi-y** [comment] 2024-04-29 14:07
Hello @178inaba, Thank you for creating this issue and we will look into it :)

**Comment by matthewrobertson** [comment] 2024-04-29 20:07
I think the issue is that https://go.dev/dl/?mode=json&include=all doesn't include `{"os": "darwin", "arch": "amd64"}` for older versions of go (versions <= 15.x.x)

**Comment by priyagupta108** [comment] 2024-05-16 08:41
Hello @178inaba👋, 
Thank you for your keen observation. I'm pleased to inform you that the `Validate setup-go` workflow issue has been addressed in our recently merged pull request ([#479](https://github.com/actions/setup-go/pull/479)). Therefore, I will be closing this issue. Your valuable contributions to our community are greatly appreciated. Thanks again:)

**Closed by priyagupta108** 2024-05-16 08:41 UTC
Labels: bug
