### ISSUE TITLE
Binaries installed via `go install` are not accessible on path 

### ISSUE THREAD

**Issue by JeremyLoy** [actions/setup-go#27] opened 2019-11-03 03:28 UTC
Hi,

I'm hoping to migrate [my open source library](https://github.com/JeremyLoy/config) from Travis to Github Actions, but I've hit a snag - I'm unable to run most of my build checks. I use [golint](https://github.com/golang/lint/) and [goimports](https://golang.org/x/tools/cmd/goimports), both tools installed via `go install`.

These binaries are not found on any OS that I've tried, (windows, ubuntu, macOS) which led me to this repo where I discovered that GOBIN was not being added to PATH.

The fix should be as simple as adding GOPATH/bin to PATH

**Comment by JeremyLoy** [comment] 2019-11-03 03:51
actually after further investigation it looks like the env and path are already getting set, but to the wrong values.

Below are some screenshots of the MacOS setup. `go env` is correctly saying that `GOPATH` is `User/runner/go`. This means that `GOBIN` will default to `User/runner/go/bin` since it is unset.

If we look at `PATH`, it seems that `/usr/local/go/bin` is getting set. By my understanding, this is not the correct value for any operating system, definitely not macOS.

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/20881794/68080119-ee9d0600-fdca-11e9-9651-c50a56cc1e2e.png">
<img width="688" alt="image" src="https://user-images.githubusercontent.com/20881794/68080132-1db37780-fdcb-11e9-9905-9c74fda7f181.png">

**Comment by kjk** [comment] 2019-11-03 03:54
I agree this should work by default by for now you can add to each step:
```
export PATH=${PATH}:`go env GOPATH`/bin
```

See https://presstige.io/p/Using-GitHub-Actions-with-Go-2ca9744b531f4f21bdae9976d1ccbb58#e86c1c15-6f43-4f43-935f-37895bd14208 for a fuller example (I use that for running staticcheck)

**Comment by devigned** [comment] 2019-11-04 00:52
https://github.com/actions/setup-go/blob/75259a5ae02e59409ee6c4fa1e37ed46ea4e5b8d/src/installer.ts#L119-L121

Should have an else and export the default `GOBIN` into the path and set the PATH to include the `GOBIN`.

**Comment by JeremyLoy** [comment] 2019-11-04 00:59
In addition to that @devigned I think the ‘GOPATH’ statement two lines above that needs an ‘else’

**Comment by devigned** [comment] 2019-11-04 01:01
Agreed. If nothing is overridden, Golang defaults should be honored.

**Comment by lmittmann** [comment] 2019-11-07 23:58
Duplicate of #14

**Comment by bryanmacfarlane** [comment] 2020-02-07 11:45
> actually after further investigation it looks like the env and path are already getting set, but to the wrong values.

Agreed.  Will fix.

**Comment by bryanmacfarlane** [comment] 2020-03-27 04:46
This should be fixed in @v2-beta version of this action.  See #14

**Closed** 2020-03-27 04:47 UTC

**Comment by ARolek** [comment] 2020-04-10 23:09
I just hit this problem and upgrading to v2-beta fixed this problem for me.

**Comment by bryanmacfarlane** [comment] 2020-04-10 23:10
Awesome to hear.  I’ll probably release v2 Monday

**Comment by ARolek** [comment] 2020-04-10 23:17
Nice! Thanks for putting this action together. I have been using it with a few projects.

**Comment by davidgraca** [comment] 2023-01-04 13:45
Hi everyone, ressurecting the dead here...
Let's start by the beggining, you:

- put that on your gh action

`- name: Setup Go environment
 uses: actions/setup-go@v3.5.0`

- go check go env

`GOPATH="/home/runner/go"`

- go check $PATH

`$PATH: /home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

- and see that all your go installs are on GOPATH /bin

I added to my action:
`export PATH=${PATH}:`go env GOPATH`/bin`

and now it works fine.
Would it be possible to refix this?
Thanks
