### ISSUE TITLE
Regex matching go-version pulls wrong version

### ISSUE THREAD

**Issue by stmcginnis** [actions/setup-go#101] opened 2021-01-26 20:48 UTC
The README gives the example of using:

```
go-version: '^1.13.1'
```

It appears there is a problem when using the `^` in the go-version specifier. When using the exact text from the example, actual job runs end up pulling in an earlier version of go:

```
Run actions/setup-go@v2
Setup go stable version spec ^1.13.1
Found in cache @ /opt/hostedtoolcache/go/1.15.6/x64
Added go to the path
Successfully setup go version ^1.13.1
go version go1.15.6 linux/amd64
```

Note the output of `^1.13.1`, but the cache hit of `/opt/hostedtoolcache/go/1.15.6/x64`.

Once the `^` is removed from the version specifier, the job correctly recognizes the right go version to use:

```
Run actions/setup-go@v2
Setup go stable version spec 1.13.1
Attempting to download 1.13.1...
matching 1.13.1...
Acquiring 1.13.1 from https://github.com/actions/go-versions/releases/download/1.13.1-20200616.23/go-1.13.1-linux-x64.tar.gz
Extracting Go...
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/c5f24668-fc8b-4cac-9a77-3f5093db058c -f /home/runner/work/_temp/61cc926c-8f03-456f-a905-aea738a8b447
Successfully extracted go to /home/runner/work/_temp/c5f24668-fc8b-4cac-9a77-3f5093db058c
Adding to the cache ...
Successfully cached go to /opt/hostedtoolcache/go/1.13.1/x64
Added go to the path
Successfully setup go version 1.13.1
go version go1.13.1 linux/amd64
```

**Comment by bojan-embroker** [comment] 2021-04-06 08:10
Isn't this correct behavior? `^1.13.1` means or newer minor or patch version.

**Comment by stmcginnis** [comment] 2021-04-06 13:16
That should be documented if that is the expected behavior. It's really unfortunate that `^` was chosen then.

With the README referring to it being a "match", and `^` being a regex match for the start of a line, the expectation was that it would only match exactly a value of `1.13.1` with nothing somehow prepended to it.

If that is not treated as a regex, and it is a symbol used to mean "or greater", then I would expect something like `+` appended to the end or something that doesn't look like a regex matching string.

Since this has been in place for some time now and there may be folks that expect that behavior, maybe the best way to resolve this at this point is to explicitly call out in the README what it means.

**Comment by bojan-embroker** [comment] 2021-04-06 13:38
`^` symbol is coming form the Node.js's dependency management world. I would say authors took as universally known syntax, but since it is not standard in Go I agree it should be better documented.

Here is the library implementing this version specification syntax that is used by setup-go:
https://www.npmjs.com/package/semver
Its documentation goes into details of `^`.

Go's versioning does not work the same Node.js does so there is some mapping between the two done by setup-to which is also not documented, but can found in the code and code comments:

https://github.com/actions/setup-go/blob/3b4dc6cbed1779f759b9c638cb83696acea809d1/src/installer.ts#L183

**Comment by Sergey-Murtazin** [comment] 2021-10-21 09:26
Hi @stmcginnis ! Sorry for the late response!
Could you please clarify if the issue is still actual for you?
Thanks!

**Comment by Sergey-Murtazin** [comment] 2021-12-02 07:48
Hi, @stmcginnis !

As written in [readme](https://github.com/actions/setup-go#v2), we are using semver notation.

You can see how to use it [here](https://devhints.io/semver)
The `^` sign means that the maximum minor version will be used.

It means that the action works correctly.

If you want to use the maximum `1.13` version, use `1.13.x` or `1.13.*`

Feel free to contact us if you have any questions.

**Comment by Sergey-Murtazin** [comment] 2021-12-15 19:25
I close this issue because it is resolved

**Closed by Sergey-Murtazin** 2021-12-15 19:25 UTC
Labels: bug
