### ISSUE TITLE
Feature request: Support built-in cache

### ISSUE THREAD

**Issue by qsliu2017** [actions/setup-go#130] opened 2021-07-17 16:32 UTC
I always use [actions/cache](https://github.com/marketplace/actions/cache) to cache the default location for cache data, and I think this should be a built-in feature of this action, like [setup-node supports dependency caching](https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching).

**Comment by sebastianst** [comment] 2022-02-17 17:43
That'd be awesome. For reference, [`actions/cache` recommends the following step in your job for Go repos (Linux)](https://github.com/actions/cache/blob/main/examples.md#go---modules):
```yaml
- uses: actions/cache@v2
  with:
    path: |
      ~/.cache/go-build
      ~/go/pkg/mod
    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    restore-keys: |
      ${{ runner.os }}-go-
```

A nice start would be to mention this `actions/cache` setup in the README.

**Comment by nc-dirknilius** [comment] 2022-03-25 07:11
It's a bit sad as this is the only `setup` action we use without build-in cache support. `setup-node` already mentioned, in addition see

https://github.com/marketplace/actions/setup-java-jdk#caching-packages-dependencies https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby#caching-bundle-install-automatically
https://github.com/marketplace/actions/setup-python#caching-packages-dependencies

**Comment by dmitry-shibanov** [comment] 2022-05-30 12:23
Hello everyone. We released the new [version](https://github.com/actions/setup-go/releases/tag/v3.2.0) of setup-go with caching support and updated major tag. For now I'm going to close the issue if you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2022-05-30 12:23 UTC
Labels: feature request

**Comment by lucacome** [comment] 2022-08-06 00:24
Hello, I replaced
```
- uses: actions/cache@v2
  with:
    path: |
      ~/.cache/go-build
      ~/go/pkg/mod
    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    restore-keys: |
      ${{ runner.os }}-go-
 ```
with the built-in cache, but seems like it's not achieving the same result, as the build time is up to 3-4 minutes form ~40s-1m.

I suspect this is because it needs to download the modules instead of using the cached ones, any ideas?

**Comment by e-korolevskii** [comment] 2022-08-10 13:30
Hello @lucacome 
Could you please open a separate issue with a detailed description and steps to reproduce it?
