### ISSUE TITLE
Multiple workflows will fight for the cache

### ISSUE THREAD

**Issue by eddycharly** [actions/setup-go#259] opened 2022-09-01 19:32 UTC
We have multiple workflows running with the same repo.
They seem to keep fighting for the same cache key.
Is there a way to have a different key per workflow ? Shall we do this or is it a bad idea ?

**Comment by e-korolevskii** [comment] 2022-09-02 15:33
Hey @eddycharly!

Thanks for this issue. You are correct that the workflows will use a same cache key.
Could you explain in more detail why you need different keys? Preferably with examples of runs.

**Comment by eddycharly** [comment] 2022-09-02 16:37
@e-korolevskii i am caching go dependencies. But those dependencies vary depending on the makefile targets invoked.
We use `go install` to install various tools.

**Comment by e-korolevskii** [comment] 2022-09-23 08:23
Hi @eddycharly 

In your case, you can try using the [cache-dependency-path input](https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs). Since this is expected behavior, I'm going to close this issue.

**Closed by e-korolevskii** 2022-09-23 08:23 UTC
Labels: question
