### ISSUE TITLE
install failure on alpine

### ISSUE THREAD

**Issue by codefromthecrypt** [actions/setup-go#263] opened 2022-09-08 07:35 UTC
**Description:**
`go: cannot find GOROOT directory: /usr/local/go` if 

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
1.18.5

**Repro steps:** 

This is a simplified version of tinygo's linux.yml in https://github.com/tinygo-org/tinygo/pull/3140
```
    runs-on: ubuntu-latest
    container:
      image: alpine:3.16
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
```

**Expected behavior:**
I would expect it to not fail

**Actual behavior:**

```
Run actions/setup-go@v3
  with:
    go-version-file: go.mod
    cache: true
    check-latest: false
    token: ***
/usr/bin/docker exec  1a481a0e1e30def1ee993d1ce10f6afd67e2b044eca2e5f372682a6997f61b7a sh -c "cat /etc/*release | grep ^ID"
Setup go version spec 1.18
Found in cache @ /__t/go/1.18.5/x64
Added go to the path
go: cannot find GOROOT directory: /usr/local/go
Error: Command failed: go env GOPATH
go: cannot find GOROOT directory: /usr/local/go
```

**Comment by dmitry-shibanov** [comment] 2022-09-08 08:05
Hello @codefromthecrypt. Thank you for your report. I think it's an expected behaviour because alpine has different structure which is not compatible with preinstalled version. The [Go for alpine image](https://github.com/docker-library/golang/blob/master/1.19/alpine3.16/Dockerfile) is built from source code.

**Comment by codefromthecrypt** [comment] 2022-09-08 08:11
so do you mean we have to basically know which version is on disk?

**Comment by codefromthecrypt** [comment] 2022-09-08 08:14
Weird thing is that actions/v2 doesn't fail when the version is set to '1.18'
https://github.com/tinygo-org/tinygo/pull/3140

![Screen Shot 2022-09-08 at 4 12 46 PM](https://user-images.githubusercontent.com/64215/189070935-045c214c-d81c-429b-b4de-7868ec36e4d4.png)

https://github.com/tinygo-org/tinygo/runs/8244431107?check_suite_focus=true

I'd love to be able to swap this with actions/v3 iotw and ideally use the new features.

**Comment by dmitry-shibanov** [comment] 2022-09-08 11:31
I mean that prebuilt versions of Go are preinstalled for hosted images but for docker's alpine images Go is installed from the source code, that is why your build fails because it uses prebuilt version in alpine which is not fully compatible. 
For now it fails because from version 3.1.0 the action does not import GOROOT env variable, because from [go 1.9](https://go.dev/doc/go1.9#goroot) it should identify it dynamically. I think due to not correct image it fails to do it and throws the error.

**Comment by codefromthecrypt** [comment] 2022-09-08 11:45
ok so if I can summarize correctly you mean to say that actions/v2 is working for the wrong reason, basically accidentally working. and that alpine will need a different solution for installing go versions, correct?

**Comment by codefromthecrypt** [comment] 2022-09-08 11:49
ps I suppose I left out a snippet where `gcompat` and `g++` packages are installed prior to using this action.

**Comment by dmitry-shibanov** [comment] 2022-09-09 13:00
Hello @codefromthecrypt. I think yes, it works but it's because we manually provide GOROOT in the v2 version but Go should make it automatically. For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2022-09-09 13:00 UTC
Labels: bug
