### ISSUE TITLE
Flakey error when running `go version`

### ISSUE THREAD

**Issue by mat285** [actions/setup-go#244] opened 2022-07-08 14:10 UTC
**Description:**
When running the action, we occasionally see an error:

```Run actions/setup-go@main
  with:
    go-version: ~1.18
    stable: true
    token: ***
  env:
    GOOS: linux
    GOARCH: amd64
    GO111MODULE: on
    CGO_ENABLED: 0
    DB_HOST: localhost
    DB_PORT: 5432
    DB_USER: postgres
    DB_PASSWORD: unit-tests
    DB_NAME: ci_db_test
    DB_SSLMODE: disable
    GHE_TOKEN: ***
Setup go stable version spec ~1.18
Attempting to download ~1.18...
matching ~1.18...
Acquiring 1.18.1 from https://github.com/actions/go-versions/releases/download/1.18.1-2171178401/go-1.18.1-linux-x64.tar.gz
Extracting Go...
/usr/bin/tar xz --warning=no-unknown-keyword -C /runner/_work/_temp/b1954076-7176-4386-bf4f-6a1bb12367dc -f /runner/_work/_temp/a66da6cf-48f5-407c-a309-7eb94d6199ce
Successfully extracted go to /runner/_work/_temp/b1954076-7176-4386-bf4f-6a1bb12367dc
Adding to the cache ...
Successfully cached go to /runner/shared/_tools/go/1.18.1/x64
Added go to the path
Successfully setup go version ~1.18
/bin/sh: 1: version: not found
Error: Command failed:  version
/bin/sh: 1: version: not found

```

This appears to be coming from here https://github.com/actions/setup-go/blob/fcdc43634adb5f7ae75a9d7a9b9361790f7293e2/src/main.ts#L47

**Action version:**
v3

**Platform:**
- [ x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ x] Self-hosted

**Tools version:**

1.18

**Repro steps:**  
Run the action. It's not consistently reproducable, only fails about 1-2% of the time

**Expected behavior:**
go version should be run without error

**Actual behavior:**
`version` command is attempted to be run since the `go` variable isn't set and thus the command isn't found

**Comment by dmitry-shibanov** [comment] 2022-07-08 21:09
Hello @mat285. Thank you for your report. We'll investigate the issue.

**Comment by panticmilos** [comment] 2022-07-12 11:34
Hi @mat285,

One question: have you noticed this behavior on any other agent besides the self-hosted one?

**Comment by e-korolevskii** [comment] 2022-08-10 13:43
Hello @mat285!

Unfortunately, we were unable to reproduce this bug, so we assume that this bug is related to the use of self-hosted agents.

I am closing this issue for now, but if you have additional questions you can always ask them here or create a new issue.
Have a good day!

**Closed by e-korolevskii** 2022-08-10 13:43 UTC
Labels: bug
